/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ContextRouteImport } from './routes/context'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as RequestsNewRouteImport } from './routes/requests_.new'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as RequestsRequestIdRunsRunIdRouteImport } from './routes/requests_.$requestId_.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => RequestsRoute,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests_/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRunsRunIdRoute =
  RequestsRequestIdRunsRunIdRouteImport.update({
    id: '/requests_/$requestId_/runs/$runId',
    path: '/requests/$requestId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/getting-started': typeof GettingStartedRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/requests': typeof RequestsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/requests/$requestId/runs/$runId': typeof RequestsRequestIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/getting-started': typeof GettingStartedRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/requests': typeof RequestsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/requests/$requestId/runs/$runId': typeof RequestsRequestIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/getting-started': typeof GettingStartedRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/requests': typeof RequestsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests_/new': typeof RequestsNewRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/requests_/$requestId_/runs/$runId': typeof RequestsRequestIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/getting-started'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/requests'
    | '/sessions'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/workspace/$id'
    | '/requests/$requestId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/getting-started'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/requests'
    | '/sessions'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/workspace/$id'
    | '/requests/$requestId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/getting-started'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/requests'
    | '/sessions'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
    | '/requests/$requestId'
    | '/requests_/new'
    | '/workspace/$id'
    | '/requests_/$requestId_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ContextRoute: typeof ContextRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  GettingStartedRoute: typeof GettingStartedRoute
  OutputsRoute: typeof OutputsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SessionsRoute: typeof SessionsRoute
  SignupRoute: typeof SignupRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
  RequestsRequestIdRunsRunIdRoute: typeof RequestsRequestIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/requests_/new': {
      id: '/requests_/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests_/$requestId_/runs/$runId': {
      id: '/requests_/$requestId_/runs/$runId'
      path: '/requests/$requestId/runs/$runId'
      fullPath: '/requests/$requestId/runs/$runId'
      preLoaderRoute: typeof RequestsRequestIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RequestsRouteChildren {
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsRequestIdRoute: RequestsRequestIdRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlueprintsRoute: BlueprintsRoute,
  ContextRoute: ContextRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  GettingStartedRoute: GettingStartedRoute,
  OutputsRoute: OutputsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SessionsRoute: SessionsRoute,
  SignupRoute: SignupRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
  RequestsRequestIdRunsRunIdRoute: RequestsRequestIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
